In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(
        df.isnull().sum()/len(df)*100,
        2
    )
})

missing_summary

                  Missing Values  Percentage
customerID                     0         0.0
gender                         0         0.0
SeniorCitizen                  0         0.0
Partner                        0         0.0
Dependents                     0         0.0
tenure                         0         0.0
PhoneService                   0         0.0
MultipleLines                  0         0.0
InternetService                0         0.0
OnlineSecurity                 0         0.0
OnlineBackup                   0         0.0
DeviceProtection               0         0.0
TechSupport                    0         0.0
StreamingTV                    0         0.0
StreamingMovies                0         0.0
Contract                       0         0.0
PaperlessBilling               0         0.0
PaymentMethod                  0         0.0
MonthlyCharges                 0         0.0
TotalCharges                   0         0.0
Churn                          0         0.0

In [6]:
for col in df.columns:

    blank_count = (
        df[col]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    if blank_count > 0:
        print(col, ":", blank_count)

TotalCharges : 11

In [7]:
problem_rows = df[
    df["TotalCharges"]
    .astype(str)
    .str.strip()
    .eq("")
]

problem_rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [9]:
problem_rows[
    [
        "customerID",
        "tenure",
        "MonthlyCharges",
        "TotalCharges",
        "Churn"
    ]
]
problem_rows["tenure"].value_counts()

tenure
0    11
Name: count, dtype: int64

### Finding: TotalCharges Quality Issue

11 records contain blank values in TotalCharges.

Investigation shows that all affected customers have tenure = 0.

Business Interpretation:
These are newly onboarded customers who have not yet generated cumulative charges.

Action Required:
Convert TotalCharges to numeric during data cleaning and handle these blank values appropriately.

In [12]:
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Customer IDs:", df["customerID"].duplicated().sum())

Duplicate Rows: 0
Duplicate Customer IDs: 0

In [13]:
dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Datatype": df.dtypes.values,
    "Unique Values": [df[col].nunique() for col in df.columns]
})

dtype_report

              Column Datatype  Unique Values
0         customerID   object           7043
1             gender   object              2
2      SeniorCitizen    int64              2
3            Partner   object              2
4         Dependents   object              2
5             tenure    int64             73
6       PhoneService   object              2
7      MultipleLines   object              3
8    InternetService   object              3
9     OnlineSecurity   object              3
10      OnlineBackup   object              3
11  DeviceProtection   object              3
12       TechSupport   object              3
13       StreamingTV   object              3
14   StreamingMovies   object              3
15          Contract   object              3
16  PaperlessBilling   object              2
17     PaymentMethod   object              4
18    MonthlyCharges  float64           1585
19      TotalCharges   object           6531
20             Churn   object              2

In [14]:
for col in df.select_dtypes(include="object").columns:
    print("\n" + "="*50)
    print(col)
    print(df[col].unique())

==================================================
customerID
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']

==================================================
gender
['Female' 'Male']

==================================================
Partner
['Yes' 'No']

==================================================
Dependents
['No' 'Yes']

==================================================
PhoneService
['No' 'Yes']

==================================================
MultipleLines
['No phone service' 'No' 'Yes']

==================================================
InternetService
['DSL' 'Fiber optic' 'No']

==================================================
OnlineSecurity
['No' 'Yes' 'No internet service']

==================================================
OnlineBackup
['Yes' 'No' 'No internet service']

==================================================
DeviceProtection
['No' 'Yes' 'No internet service']

==================================================
TechSupport
['No' 'Yes' 'No internet service']

==================================================
StreamingTV
['No' 'Yes' 'No internet service']

==================================================
StreamingMovies
['No' 'Yes' 'No internet service']

==================================================
Contract
['Month-to-month' 'One year' 'Two year']

==================================================
PaperlessBilling
['Yes' 'No']

==================================================
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

==================================================
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

==================================================
Churn
['No' 'Yes']

In [15]:
summary = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Blank TotalCharges",
        "Duplicate Rows",
        "Duplicate Customer IDs"
    ],
    "Value": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        (df["TotalCharges"].astype(str).str.strip() == "").sum(),
        df.duplicated().sum(),
        df["customerID"].duplicated().sum()
    ]
})

summary

                   Metric  Value
0                    Rows   7043
1                 Columns     21
2          Missing Values      0
3      Blank TotalCharges     11
4          Duplicate Rows      0
5  Duplicate Customer IDs      0